MainMenu/urls.py
from django.urls import path
from .views import  Home

app_name ='mainmenu'

urlpatterns = [
	path('', Home, name = 'home'),
]

TuPPW1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainMenu.urls')),
    path('', include('bartrans.urls')),
    path('account/', include('account.urls')),
    path('coupon/',include('coupon.urls')),
    path('',include('ulasan.urls', namespace="reviewName")),
    path('', include('social_django.urls',namespace='social')),
    # path('cart/',include('cart.urls'),name="cart"),
]

account/urls.py
from django.urls import path
from account import views

app_name = 'account'

urlpatterns =[
    path('signup/', views.signup, name = 'signup'),
    path('login/', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name ='logout'),
]

cart/urls.py
from django.urls import path, include
from . import views

app_name = 'cart'
# urlpatterns = [
#     path('', views.detail, name="detail"),
#     path('create/',views.create, name="create"),
#     path('min/',views.min, name="min"),
#     path('add/',views.add, name="add"),
# ]

coupon/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='coupon'),
    path('search/', views.searchObjects),
]

ulasan/urls.py
from django.urls import path, include
from . import views

app_name = "reviewName"

urlpatterns = [
    # path('',views.index, name='ulasan'),
    path('ulasan/', views.reviews, name='reviews'),
]

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from MainMenu.models import Barang

# Create your models here.
# class TransaksiBarang(models.Model):
#     barang = models.ForeignKey(Barang, on_delete=models.CASCADE)
#     jumlah = models.PositiveIntegerField()

#     def __str__(self):
#         return f"{self.barang.nama} ({self.jumlah})"

# class Keranjang(models.Model):
#     nama_keranjang = models.OneToOneField(User, on_delete=models.CASCADE)
#     isi_keranjang = models.ManyToManyField(TransaksiBarang)

#     def __str__(self):
#         return "{self.nama_keranjang} cart"

coupon/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
import datetime

# Create your models here.
class Coupon(models.Model):
    kode = models.CharField(max_length=50,unique=True)
    tanggal = models.DateTimeField()
    diskon = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(100)])
    minimum = models.IntegerField()

    def __str__(self):
        return self.kode

    def as_json(self):
        return dict(
            id=self.id, kode=self.kode,
            tanggal=self.tanggal.isoformat(), 
            diskon=self.diskon,
            minimum=self.minimum)

ulasan/models.py
from django.db import models
from bartrans.models import trans

# Create your models here.
class Reviews(models.Model):
    pembeli = models.CharField(blank=False, max_length= 100)
    daftar_rate = (
        ('1', 'Bintang Satu'),
        ('2', 'Bintang Dua'),
        ('3', 'Bintang Tiga'),
        ('4', 'Bintang Empat'),
        ('5', 'Bintang Lima'),
    )
    daftar_barang = trans.objects.values_list('id','nama')
    rate = models.CharField(max_length=1)
    barang = models.CharField(max_length=30)
    pesan = models.CharField(blank=False, max_length= 100)
    tanggal = models.DateField('Date', auto_now_add=True)

    # trans = models.ForeignKey(trans, on_delete=models.CASCADE)

ulasan/forms.py
from django import forms
from bartrans.models import trans

daftar_rate = [
        ('1', 'Bintang Satu'),
        ('2', 'Bintang Dua'),
        ('3', 'Bintang Tiga'),
        ('4', 'Bintang Empat'),
        ('5', 'Bintang Lima'),
]
daftar_barang = trans.objects.values_list('nama','nama')

class review(forms.Form):
    pembeli = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Nama Pembeli',
        'type' : 'text',
        'required' : True
    }))
    rate = forms.CharField(label='Pilih Rate', widget=forms.Select(choices=daftar_rate , attrs={
    'class' : "form-control",
    'required' : True
    }))
    barang = forms.CharField(label='Pilih Barang', widget=forms.Select(choices=daftar_barang , attrs={
    'class' : "form-control",
    'required' : True
    }))
    pesan = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Pesan',
        'type' : 'text',
        'required' : True
    }))
    # tanggal = forms.DateField(widget=forms.SelectDateWidget(attrs={
    #     'class' : 'form-control',
    #     'placeholder' : 'Pilih Tanggal',
    #     'required' : True
    # }))
    # tanggal = forms.DateField(label='What is your birth date?', widget=forms.SelectDateWidget)

cart/views.py
# from django.shortcuts import render, redirect
# from django.contrib.auth.models import User
# from django.http import JsonResponse, HttpResponse
# from django.views.decorators.csrf import csrf_exempt
# from django.shortcuts import get_object_or_404
# from MainMenu.models import Barang
# from .models import Keranjang, TransaksiBarang

# # Create your views here.
# @csrf_exempt
# def detail(request):
#     krj_user = Keranjang.objects.get(nama_keranjang=request.user)
#     brg_user = [ {"nama" : barangs.barang.nama, "harga" : barangs.barang.harga, "stok" : barangs.jumlah, "stock_asli" : barangs.barang.stok, "ids" : barangs.id} for barangs in krj_user.isi_keranjang.all()]
#     return JsonResponse({'data':brg_user})

    

# @csrf_exempt
# def min(request):
#     if request.method=="POST":
#         idns = request.POST['id_target']
#         productobj= get_object_or_404(TransaksiBarang, id=idns)
#         barang_target = Keranjang.objects.get(nama_keranjang=request.user)
#         if productobj.jumlah == 1:
#             barang_target.isi_keranjang.remove(productobj)
#         else :
#             productobj.jumlah -= 1
#             productobj.save()
#         return JsonResponse({'foo':'bar'})

# @csrf_exempt
# def add(request):
#     if request.method=="POST":
#         idns = request.POST['id_target']
#         productobj= get_object_or_404(TransaksiBarang, id=idns)
#         barang_target = Keranjang.objects.get(nama_keranjang=request.user)
#         if productobj.barang.stok == productobj.jumlah:
#             return JsonResponse({'foo':'bar'})
#         else:
#             productobj.jumlah += 1
#             productobj.save()
#             return JsonResponse({'foo':"bar"})

# @csrf_exempt
# def create(request):
#     if request.method=="POST":
#         barang_dibeli = Barang.objects.get(nama=request.POST["namabarang"])
#         result = Keranjang.objects.get(nama_keranjang=request.user)
#         total = [barangs.barang.nama for barangs in result.isi_keranjang.all()]
#         if barang_dibeli.nama in total:
#             target = TransaksiBarang.objects.get(barang=barang_dibeli)
#             target.jumlah += 1
#             target.save()
#             return JsonResponse({"foo" : "bar"})
#         else :
#             item = TransaksiBarang(barang=barang_dibeli,jumlah=1)
#             item.save()
#             keranj = Keranjang.objects.get(nama_keranjang=request.user)
#             keranj.isi_keranjang.add(item)
#             keranj.save()
#             return JsonResponse({"foo" : "bar"})
        

coupon/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.core.serializers import serialize
# from django.core import serializers
from .models import Coupon

 
def index(request):
    qs = Coupon.objects.all()
    context = {
        'queryset' : qs,
    }
    return render(request, 'coupon.html', context)

def searchObjects(request):
    allObject_list = list(Coupon.objects.values())
    print(allObject_list)
    # serialize('json', allObject_list)
    # isi = serialize('json', allObject_list)
    return JsonResponse(allObject_list, safe=False)

ulasan/views.py
from django.shortcuts import render, redirect
from .models import Reviews
from .forms import review

# Create your views here. 
# def index(request):
#     qs = Reviews.objects.all()
#     return render(request, 'ulasan.html', {'review':review})

def reviews(request):
    if(request.method == "POST"):
        tmp = review(request.POST)
        pembeli = request.POST["pembeli"]
        rate = request.POST["rate"]
        barang = request.POST["barang"]
        pesan = request.POST["pesan"]
        tmp2 = Reviews(pembeli=pembeli, rate=rate, barang=barang,pesan=pesan)
            # tmp2.tanggal = tmp.cleaned_data["tanggal"]
        tmp2.save()
        return redirect("/ulasan")
    else:
        tmp = review()
        tmp2 = Reviews.objects.all()
        tmp_dictio = {
            'review' : tmp,
            'reviews' : tmp2
        }
        #sprint("ini tmp 2 : ",tmp2)
        return render(request, 'ulasan.html', tmp_dictio)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- Bootstrap CSS -->
    

    

    <title>{% block title %} {% endblock %}</title>
    {% load static %}
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.js"></script>


  </head>
  <body style="background-color: #f7f7f7">
    
     {% include "navbar.html" %}
    

    
      <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Keranjang</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            

            </div>
            <div class="modal-footer d-flex flex justify-content-between">
                <div class="untuk-harga">
  
                </div>
  
               
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

      {% block content %}
      {% endblock %}
    
      
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script> -->

   <!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script> -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="{% static 'js/pre-cart.js' %}"></script>    

<script src="{% static 'js/trans.js' %}"></script>   
<script src="{% static 'js/cart.js' %}"></script>    
<script src="{% static 'js/beli.js' %}"></script>    

<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/coupon.js' %}"></script>  
<script src="{% static 'js/jquery.autocomplete.js' %}"></script>
  </body>
</html>

templates/beli.html
{% extends 'base.html' %}
{% block title %} {{data.nama}} {% endblock %}
{% block content %}
{%load static%}
<script src="{% static 'js/beli.js' %}"></script>    

<br><br><br>
<div class="container" style="color: black">
	<ul class="messages">
		{% for msg in messages %}
				<div class="alert alert-{{msg.level_tag}}" role="alert">
					{{msg.message}}
				</div>
			
		{% endfor %}
	</ul>
    <div class="row">
        <div class="col-lg-6 col-sm-12" style="align-content: center;align-self: center;align-items: center;">
            <img src="/{{data.image}}" alt="{{data.nama}}" style="border-radius: 20%"><br>
            <!-- <h1>{{data.nama}}</h1>
            <h1>Rp.{{data.harga}}</h1> -->
        </div>
        <div class="col-lg-6">
		</br></br>
		<b><h1 class ="nama_barang" id ="{{data.nama}}">{{data.nama}}</h1></b>
			<h2>Rp.{{data.harga}}</h2>
			<h5><a href="">⭐⭐⭐⭐⭐</h5></a>
				</br>
				

				<div class="shop-item-details">
						{% if request.user.is_authenticated %}
						Tersisa :  {{data.stok}} </BR>
						<input type="submit" id="tambah" class="button" value="ADD TO CART !">
					  {%else%}

					  <form  action="{% url 'cekharga' pk=data.pk %}" method="post" style="align-content: left; text-align: left; align-self: left;"> 
	    		{% csrf_token %}
		    		<div class="form-group">
		        	<label>Nama:</label>
		        	 {{form.nama}}
		        	</div> 
		            <div class="form-group">
		        	<label>kupon:</label>
		        	 {{form.kupon}}
		        	</div> 
	            <button type="submit" class="btn btn-success" name="cek">cekharga</button>

             <button type="submit" class="btn btn-success" name="beli">beli</button> 
				 </form> 
				</br>
				 <h5>
				 </br> <a href={% url 'account:login' %} class="btn btn-primary">Log In</a> untuk menambah ke CART</h5>
				
						{%endif%}
				  </div>
        </div>
    </div>
    <br>
</div>
<br><br><br>

  {% endblock %}
  <!--cekharga masukkan form.kupon kupon dari winalton sama primary key barang-->

        	<!--<form  action="{% url 'cekharga' %}" method="post" style="align-content: left; text-align: left; align-self: left; color: white">
    		{% csrf_token %}-->

templates/cart.html
{% extends 'base.html' %}
{% block title %}Cart{% endblock %}
{% load static %}

{% block content %}
<script src="{% static 'js/cart.js' %}"></script>    
<!-- <link rel="stylesheet" type="text/css" href="{% static 'css/cart.css' %}">
<h1>CART</h1>
</BR>
</br>
<table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Item</th>
                <th scope="col">@Price (Rp)</th>
                <th scope="col">Quantity</th>
    
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for qs in keranjang %}
            {% for barang in qs.isi_keranjang.all %}
            <tr id="{{barang}}">
                <td></td>
                <td>{{barang}}</td>
                <td>{{barang.harga}}</td>
                <td class="kuantitas_{{barang}} row" id="{{barang.kuantitas}}">
                    <div class="col-2 kuantitas">
                        {{barang.kuantitas}}
                    </div>
    
    
                    <div class="col-9">
                        <button style="width: 40px; height: 40px;" class="btn btn-warning tambah" role="button">+</button>
                        <button style="width: 40px; height: 40px;" class="btn btn-warning kurang" role="button">-</button>
                        </>
    
                </td>
                <td><button class="btn buang">a</button></td>
            </tr>
            {% endfor %}
            {% endfor %}
        </tbody>
    </table> -->

<!-- <section class="container content-section">
    <h2 class="section-header">CART</h2>
    <div class="cart-row">
        <span class="cart-item cart-header cart-column">ITEM</span>
        <span class="cart-price cart-header cart-column">PRICE</span>
        <span class="cart-quantity cart-header cart-column">QUANTITY</span>
    </div>
    <div class="cart-items">
    </div>
    <div class="cart-total">
        <strong class="cart-total-title">Total</strong>
        <span class="cart-total-price">Rp. 0</span>
    </div>
    <button class="btn btn-primary btn-purchase" type="button">PURCHASE</button>
</section> -->

{% endblock %}

templates/coupon.html
{% extends 'base.html' %}
{% block title %}Coupon{% endblock %}
{% block content %}
<br><br><br>
<div style="text-align:center">
<h3>Berikut adalah kupon-kupon yang disediakan oleh <b>Tokopepewia</b></h3>
<h4>Tersedia {{queryset|length}} kupon</h4></br>
</div>

<!-- <form id="searchForm" action="javascript:search();">
  <div class="input-group">
     <button id="go" class="btn btn-default" type="button" 
             onclick="document.getElementById('searchForm').submit(); return false;">
     </button>
     <input type="text" id="searchItem" class="form-control" placeholder="Cari kupon kamu disini / Tekan (CTRL +F) pada keyboard.">
  </div>
</form> -->
<!-- <input type="text" id="ajax" list="json-datalist" placeholder="e.g. 20"> -->
<div class="autocomplete" style="width:300px;">
  <label for="myInput" id="myInputt">Diskon: </label>
  <!-- <input id="myInput" type="text" name="myCountry" placeholder="Diskonn"> -->
  <input id="myInput" placeholder="Masukkan angka saja. Contoh: 20">
  <div id="result"></div>
</div>

</br></br>
<div class="container">
      <div id="kupon" class=""></div>
        <div class="d-flex flex-row flex-wrap justify-content-center">
          {% for kupon in queryset %}
          <div class="card m-3 d-flex flex-wrap text-align-center">
            <div class="card-body">
              <h5 class="card-title">DISKON {{kupon.diskon}}%</h5>
              <p class="card-text">Min price: {{kupon.minimum}}</p>
              <p class="card-text">Expire: {{kupon.tanggal}}</p>
              <p class="card-text">Kode kupon:</p>
              <h3 class="card-text" id="{{kupon.kode}}">{{kupon.kode}}</h3>
              <button style="background-color: grey" onclick="copyToClipboard('#{{kupon.kode}}')"><b>COPY KODE COUPON</B></button>  
            </div>
          </div>
          {% endfor %}
      </div>
  </div>
  <script>
  function copyToClipboard(element) {
    var $temp = $("<input>");
    $("body").append($temp);
    $temp.val($(element).text()).select();
    document.execCommand("copy");
    $temp.remove();
  }
  </script>

<script>
  function search() {
   
     var name = document.getElementById("searchForm").elements["searchItem"].value;
     var pattern = name.toLowerCase();
     var targetId = "";
   
     var divs = document.getElementsByClassName("container");
     for (var i = 0; i < divs.length; i++) {
        var para = divs[i].getElementsByTagName("h3");
        var index = para[0].innerText.toLowerCase().indexOf(pattern);
        if (index != -1) {
           targetId = divs[i].parentNode.id;
           document.getElementById(targetId).scrollIntoView();
           break;
        }
     }  
  }
  </script>

  {% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{%block title%}Login{%endblock%}
{% block content %}
<br><br><br>
<div class='container'>
    <div class='container'>
        <h2>Log In</h2>
        <br>
        {%if request.GET.next%}
        <p>It's look like you are not logged in, please log in first.</p>
        {%endif%}
        <form method="post" action="{%url 'account:login' %}" novalidate>
            {% csrf_token %}
            <div class='col-md-4'>
                {{form.username|as_crispy_field}}
            </div>
            <div class='col-md-4'>
                {{form.password|as_crispy_field}}
            </div>
            <div class ='col-md-4'>
            <button type="submit" class='btn btn-primary'>Log In</button>
            <p><small>Don't have an account? <a href="{%url 'account:signup' %}" style="color:red;">Register here.</a></small></p>
            </div>
        </form>
        <a class='btn btn-danger' href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a>
    
    </div>
</div>
{% endblock %}

templates/navbar.html
<div class="container">
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark" style="background-color: #ff1344">
    <a class="navbar-brand" href="{% url 'mainmenu:home' %}">TOKOPEPWIA</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown" style="background-color: #ff1344">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link {% if nbar == 'home'%} active {%endif%}" href="{% url 'mainmenu:home' %}">HOME</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'transaksi' %}">TRANSAKSI</a>
        </li>
        <li class="nav-item">
          <a class="nav-link pull-right" href="/coupon/">KUPON</a>
        </li>
        <li class="nav-item disabled">
          <a class="nav-link pull-right" href="/ulasan">ULASAN</a>
        </li>
        {%if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link pull-right" href="{% url 'transaksiku' %}">TRANSAKSIKU</a>
        </li>
        {%endif%}
      </ul>
      <div class="navbar-nav ml-auto">
        {%if user.is_authenticated %}
        
        <li class="nav-item">
          <!-- <a class="nav-link pull-right" href="/cart/">CART</a> -->
          <button type="button" class="modal_keranjang btn btn-primary" data-toggle="modal" data-target="#exampleModal">
              Cart
            </button>
        </li>
        <form class="form-inline" method='post' action="{%url 'account:logout' %}">
          {% csrf_token %}
          <button class="btn btn-outline-danger mx-3" type="submit">Log Out</button>
        </form>
        {% else %}
        <a href={% url 'account:login' %} class="btn btn-primary">Log In</a>
        <a href={% url 'account:signup' %} class="btn btn-secondary mx-3" >Register</a>
        {% endif%}
      </div>
    </div>
  </nav>      
</div>

templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{%block title%}Register{%endblock%}
{% block content %}
<br><br><br>
<div class='container'>
    <div class='container'>
        <h2>Register</h2>
        <br>
        <a class='btn btn-danger' href="{% url 'social:begin' 'google-oauth2' %}">Register with Google</a>
        <br>
        <br>
        <form method="post" novalidate>
            {% csrf_token %}
            <div class='col-sm-4'>
                {{form.username|as_crispy_field}}
                <small class='pt-0 text-muted '>username can't be change</small>
            </div>
            <div class='col-sm-4'>
                {{form.first_name|as_crispy_field}}
            </div>
            <div class='col-sm-4'>
                {{form.last_name|as_crispy_field}}
            </div>
            <div class='col-sm-4'>
                {{form.email|as_crispy_field}}
            </div>
            <div class='col-sm-4'>
                {{form.password1|as_crispy_field}}
            </div>
            <div class='col-sm-4'>
                {{form.password2|as_crispy_field}}
            </div>
            <button type="submit" class='btn btn-primary'>Register</button>
            <p><small>Already have an account? <a href="{%url 'account:login' %}" style="color:red;">Log In here</a>.</small></p>
        </form>
    </div>
</div>
{% endblock %}

templates/transaksi.html
{% extends 'base.html' %}
{% block title %} transaksi {% endblock %}
{% block content %}
<br><br><br>
<div class="container">
    <div class="row">
      <div class="col-lg-12 ">
        <table class="table table-striped table-dark" style=" float: center;" >
        	<tbody>
        		{% for j in data %}
        		<tr>
        			<td>{{ j.nama }}</td>
        			<td>{{ j.barang }}</td>
        			<td><img src="/{{j.image}}" alt="{{j.}}" style="border-radius: 20%;width: 100px"></td>
        			<td>Rp.{{ j.harga }}</td>
        			<td>{{ j.kupon }}</td>
        			<td>{{ j.tanggal }}</td>
        		</tr>
        		{% endfor %}
        	</tbody>
        </table>
      </div>
  </div>
<br><br><br>
{% endblock %}

templates/transaksiku.html
{% extends 'base.html' %}
{% block title %} transaksiku {% endblock %}
{% block content %}
<br><br><br>
<div class="container">
    <div class="row">
      <div class="col-lg-12 ">
        <table class="table table-striped table-dark" style=" float: center;" >
        	<tbody>
        		{% for j in data %}
        		<tr>
                    <td>{{ j.tanggal }}</td>
        			<td>{{ j.barang }}</td>
        			<td><img src="/{{j.image}}" alt="{{j.}}" style="border-radius: 20%;width: 100px"></td>
        			<td>Rp.{{ j.harga }}</td>
                    <td>{{ j.jumlah }}</td>
                    <td>Rp.{{ j.hargadisc }}</td>
        			
        		</tr>
        		{% endfor %}
                
        	</tbody>
        </table>
      </div>
  </div>
<br><br><br>
{% endblock %}

templates/ulasan.html
{% extends 'base.html' %}
{% block title %}home {% endblock %}
{% block content %}
<br><br>
<div class="container">
      <div id="kupon" class=""></div>
      <form method="POST" action="{% url 'reviewName:reviews' %}">
        <br><br><br>
        {% csrf_token %}

        {{review}}

        <button type="submit", >ADD</button>
         </form>
         <br><br>
         <h2 class="card-title">Ulasan Terkini</h2>
         <div class="d-flex flex-row flex-wrap justify-content-center">
          {% for ulasan in reviews %}
          <div class="card m-3 d-flex flex-wrap text-align-center">
            <div class="card-body">
              <h4 class="card-title">{{ulasan.barang}}</h4>
              <p class="card-text">oleh {{ulasan.pembeli}}</p>
              <h5 class="card-text">Rate = {{ulasan.rate}}/5</h5>
              <p class="card-text">{{ulasan.pesan}}</p>
              <p class="card-text">{{ulasan.tanggal}}</p>
              <!-- <a href="#" class="btn btn-primary">Gunakan</a> -->
            </div>
          </div>
          {% endfor %}
      </div>
  </div>

{% endblock %}